- Cargo.toml
- README.md
- examples/layers/examples/recommended_layers.rs
- examples/layers/examples/signer_layer.rs
- examples/providers/Cargo.toml
- examples/subscriptions/Cargo.toml
- examples/transactions/examples/transfer_erc20.rs
- examples/wallets/examples/ledger_signer.rs
- examples/wallets/examples/trezor_signer.rs
- examples/wallets/examples/yubi_signer.rs
Updates to latest Alloy commit: `f7333c4` and fixes breaking changes
Adds a `.with_recommended_layers()` example and a few additional comments
> feat(layers): add recommended layers example

- Cargo.toml
- examples/anvil/Cargo.toml
- examples/contracts/Cargo.toml
- examples/layers/Cargo.toml
- examples/providers/Cargo.toml
- examples/queries/Cargo.toml
- examples/subscriptions/Cargo.toml
- examples/transactions/Cargo.toml
- examples/transactions/examples/trace_call.rs
- examples/wallets/Cargo.toml
> chore(general): remove reqwest dependency

- README.md
Had some people reaching out not aware of the Telegram group, figured it made sense to add it here as well.
Adds the links and well as points to the general contribution guide.
> chore(readme): add Telegram link and additional information for contributing

- .github/CODEOWNERS
We should have automatic review pings for any new PRs on the repo
Add a CODEOWNERS file
> feat(`github`): add CODEOWNERS

- CONTRIBUTING.md
- Cargo.toml
Upgrades to commit: https://github.com/alloy-rs/alloy/commit/44c905de538fb7bbd54cad0a852a2c52392b8778
> chore: upgrade to `44c905d`

- Cargo.toml
- examples/wallets/Cargo.toml
- examples/wallets/examples/aws_signer.rs
> feat(wallets): aws signer

- README.md
- examples/transactions/examples/with_access_list.rs
- examples/wallets/examples/aws_signer.rs
Small fixes following #65 and #66
> chore(general): minor fixes to examples

- Cargo.toml
- examples/anvil/examples/deploy_contract_anvil.rs
- examples/contracts/examples/deploy_from_artifact.rs
- examples/contracts/examples/deploy_from_contract.rs
- examples/contracts/examples/interact_with_abi.rs
- examples/fillers/examples/gas_filler.rs
- examples/fillers/examples/nonce_filler.rs
- examples/fillers/examples/recommended_fillers.rs
- examples/fillers/examples/signer_filler.rs
- examples/providers/examples/builder.rs
- examples/providers/examples/http.rs
- examples/queries/examples/query_contract_storage.rs
- examples/queries/examples/query_deployed_bytecode.rs
- examples/queries/examples/query_logs.rs
- examples/transactions/examples/gas_price_usd.rs
- examples/transactions/examples/sign_transaction.rs
- examples/transactions/examples/trace_call.rs
- examples/transactions/examples/trace_transaction.rs
- examples/transactions/examples/transfer_erc20.rs
- examples/transactions/examples/transfer_eth.rs
- examples/transactions/examples/with_access_list.rs
- examples/wallets/examples/keystore_signer.rs
- examples/wallets/examples/ledger_signer.rs
- examples/wallets/examples/private_key_signer.rs
- examples/wallets/examples/trezor_signer.rs
- examples/wallets/examples/yubi_signer.rs
Fixes: https://github.com/alloy-rs/examples/actions/runs/8840957789/job/24277226318
Applies required changes from: https://github.com/alloy-rs/alloy/commit/bbef8de3fd203bf6feb26dc619f42b2bb2ecd4e3
> chore(general): update to `bbef8de`

- examples/contracts/examples/deploy_from_bytecode.rs
This example shows how to deploy bytecode at runtime. This could be useful for dynamically deploying and testing contracts.
> Add example of run time bytecode deployment

- .github/workflows/integration.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- Cargo.toml
- examples/contracts/examples/deploy_from_bytecode.rs
- examples/fillers/examples/gas_filler.rs
- examples/fillers/examples/nonce_filler.rs
- examples/fillers/examples/recommended_fillers.rs
- examples/fillers/examples/signer_filler.rs
- examples/providers/examples/builtin.rs
- examples/providers/examples/ws.rs
- examples/providers/examples/ws_with_auth.rs
- examples/queries/examples/query_contract_storage.rs
- examples/queries/examples/query_deployed_bytecode.rs
- examples/subscriptions/examples/event_multiplexer.rs
- examples/subscriptions/examples/subscribe_blocks.rs
- examples/transactions/examples/gas_price_usd.rs
- examples/transactions/examples/send_eip4844_tx.rs
- examples/transactions/examples/trace_call.rs
- examples/transactions/examples/with_access_list.rs
- examples/wallets/examples/aws_signer.rs
Bump alloy.
Bump and remove unnecessary `BlockId:latest()` calls.
> chore: bump alloy

- README.md
- examples/wallets/examples/verify_message.rs
Closes #81 
Adds `verify_message` example to wallets category
> Add verify message example

- .github/workflows/integration.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- README.md
- examples/subscriptions/examples/subscribe_pending_transactions.rs
> Add example of listening to mempool

- examples/anvil/examples/deploy_contract_anvil.rs
- examples/contracts/examples/deploy_from_artifact.rs
- examples/contracts/examples/deploy_from_bytecode.rs
- examples/contracts/examples/deploy_from_contract.rs
- examples/fillers/examples/nonce_filler.rs
- examples/transactions/examples/transfer_erc20.rs
- examples/transactions/examples/with_access_list.rs
- examples/wallets/examples/keystore_signer.rs
- examples/wallets/examples/ledger_signer.rs
- examples/wallets/examples/private_key_signer.rs
- examples/wallets/examples/trezor_signer.rs
- examples/wallets/examples/yubi_signer.rs
Shows light-weight best practice
> Prefer `watch` instead of `get_receipt` if only a transaction hash is required

- Cargo.toml
- examples/anvil/examples/deploy_contract_anvil.rs
- examples/contracts/examples/deploy_from_artifact.rs
- examples/contracts/examples/deploy_from_bytecode.rs
- examples/contracts/examples/deploy_from_contract.rs
- examples/sol-macro/examples/events_errors.rs
- examples/sol-macro/examples/structs_enums.rs
- examples/subscriptions/examples/subscribe_pending_transactions.rs
- examples/transactions/examples/with_access_list.rs
Enforce: https://rust-lang.github.io/rust-clippy/master/#/uninlined
> chore(clippy): enhance clippy rules and enforce `uninlined_format_args`

- Cargo.toml
- examples/providers/examples/ipc.rs
- examples/providers/examples/ws.rs
- examples/providers/examples/ws_with_auth.rs
- examples/subscriptions/examples/event_multiplexer.rs
- examples/subscriptions/examples/poll_logs.rs
- examples/subscriptions/examples/subscribe_all_logs.rs
- examples/subscriptions/examples/subscribe_blocks.rs
- examples/subscriptions/examples/subscribe_logs.rs
- examples/subscriptions/examples/subscribe_pending_transactions.rs
See: https://github.com/alloy-rs/alloy/pull/877
Uses the new `full` flag and the `WsConnect` and `IpcConnect` exports now available in the provider namespace.
> feat(alloy): use `full` flag and optimize flag use

- Cargo.toml
- examples/anvil/examples/deploy_contract_anvil.rs
- examples/contracts/examples/deploy_from_artifact.rs
- examples/contracts/examples/deploy_from_bytecode.rs
- examples/contracts/examples/deploy_from_contract.rs
- examples/fillers/examples/gas_filler.rs
- examples/fillers/examples/nonce_filler.rs
- examples/fillers/examples/recommended_fillers.rs
- examples/fillers/examples/signer_filler.rs
- examples/providers/examples/builder.rs
- examples/transactions/examples/send_private_transaction.rs
- examples/transactions/examples/send_raw_transaction.rs
- examples/transactions/examples/transfer_eth.rs
- examples/wallets/examples/aws_signer.rs
- examples/wallets/examples/create_keystore.rs
- examples/wallets/examples/keystore_signer.rs
- examples/wallets/examples/ledger_signer.rs
- examples/wallets/examples/mnemonic_signer.rs
- examples/wallets/examples/private_key_signer.rs
- examples/wallets/examples/sign_message.rs
- examples/wallets/examples/sign_permit_hash.rs
- examples/wallets/examples/trezor_signer.rs
- examples/wallets/examples/verify_message.rs
- examples/wallets/examples/yubi_signer.rs
See: https://github.com/alloy-rs/alloy/pull/883
Closes: https://github.com/alloy-rs/examples/issues/92
- Updates documentation
- Updates examples to reflect changes
> chore(general): update wallets and signers naming

- .github/workflows/integration.yml
- Cargo.toml
Closes #111 
Also updates the integration workflow to handle the change in format, still runs the integration tests against the latest commit
> chore(deps): update and pin to alloy `0.1.*`

- examples/wallets/examples/private_key_signer.rs
`LocalWallet` -> `PrivateKeySigner`
> fix: update stale comment

- CONTRIBUTING.md
To reflect the policy changes as stated in https://github.com/alloy-rs/alloy/pull/764
> chore: update contribution guide regarding spelling mistakes

- Cargo.toml
> chore(deps): bump to Alloy `0.2.0`

- examples/contracts/examples/interact_with_abi.rs
- examples/sol-macro/examples/user_defined_types.rs
- examples/transactions/examples/with_access_list.rs
Closes https://github.com/alloy-rs/examples/issues/124
> chore: make some code more idiomatic

- Cargo.toml
Bump to https://github.com/alloy-rs/alloy/releases/tag/v0.2.1
> chore: bump `alloy` to 0.2.1

- examples/contracts/Cargo.toml
- examples/contracts/examples/jsonrpc_error_decoding.rs
> feat: add custom jsonrpc error decoding example

- Cargo.toml
- examples/fillers/examples/nonce_filler.rs
Updates Alloy to `0.3.1`
Minor fix for new `simple` / `cached` nonce management that was a breaking change.
> deps: bump Alloy to `0.3.1`

- README.md
- examples/node-bindings/examples/anvil_set_storage_at.rs
This example shows how to mock storage values after forking with Anvil. It's useful for running local simulations.
> feat: node-bindings alloy api example

- examples/transactions/examples/send_eip7702_transaction.rs
Closes: #138 
Uses the new `TransactionBuilder7702` (to match `TransactionBuilder4844` usage)
Converted it into an Alice / Bob example
I verified the output receipt is the same but please perform a sanity check @yash-atreya
> chore: update send eip7702 transaction

- Cargo.toml
- examples/advanced/examples/foundry_fork_db.rs
- examples/comparison/examples/compare_new_heads.rs
- examples/fillers/examples/gas_filler.rs
- examples/fillers/examples/nonce_filler.rs
- examples/fillers/examples/recommended_fillers.rs
- examples/layers/Cargo.toml
- examples/providers/examples/builtin.rs
- examples/providers/examples/ws.rs
- examples/providers/examples/ws_with_auth.rs
- examples/subscriptions/examples/subscribe_blocks.rs
- examples/transactions/examples/encode_decode_eip1559.rs
- examples/wallets/Cargo.toml
alloy 0.6.2
Bumps alloy + revm + foundry-fork-db (patch)
> chore(deps): bump alloy 0.6.2 

- Cargo.toml
- README.md
- examples/layers/Cargo.toml
- examples/layers/examples/hyper_http_layer.rs
Demonstrate how to implement a tower layer that can be used with the `HyperClient`  to modify requests.
Write a custom `RequestModifyingLayer`
> feat(`layers`): hyper layer

- Cargo.toml
- examples/advanced/Cargo.toml
- examples/advanced/examples/reth_db_layer.rs
- examples/advanced/examples/reth_db_provider.rs
Reverts alloy-rs/examples#170, ref: https://github.com/alloy-rs/examples/pull/170#issuecomment-2575637536
I'll create a PR w/ fixes (if required) once 0.10 has been released
> Revert "chore(deps): alloy 0.10"

- Cargo.toml
- README.md
- examples/providers/examples/abi/IWETH9.json
- examples/providers/examples/multicall.rs
Demonstrate how to use the `MulticallBuilder` API. Ref https://github.com/alloy-rs/alloy/pull/2010
> feat: multicall

- Cargo.toml
- examples/advanced/examples/foundry_fork_db.rs
- examples/comparison/examples/compare_new_heads.rs
- examples/comparison/examples/compare_pending_txs.rs
- examples/contracts/examples/jsonrpc_error_decoding.rs
- examples/providers/examples/builtin.rs
- examples/providers/examples/wrapped_provider.rs
- examples/transactions/examples/gas_price_usd.rs
- examples/transactions/examples/trace_call.rs
Bump alloy to latest
- Bump to alloy 0.2 
- Address breaking changes
Needs:
- alloy 0.2 release (using patch currently)
- https://github.com/foundry-rs/foundry-fork-db/pull/43
> chore(deps): alloy 0.2

- Cargo.toml
- README.md
- examples/contracts/examples/jsonrpc_error_decoding.rs
- examples/contracts/examples/revert_decoding.rs
Closes #179 
Demonstrate `contract::Error` methods:
- `as_revert_data`
- `as_decoded_error`
- `as_decoded_interface_error`
> feat(`contracts`): decoding revert data

- Cargo.toml
- examples/transactions/examples/decode_receipt_log.rs
Demonstrate how to decode logs present in a transaction receipt.
Decoding using newly introduced `decoded_log` fn in https://github.com/alloy-rs/alloy/pull/2086
> feat: decoding log from a receipt

- Cargo.toml
- examples/layers/Cargo.toml
- examples/layers/examples/fallback_layer.rs
Provides an example for https://github.com/alloy-rs/alloy/pull/2135.
> feat: `FallbackLayer` example

- README.md
- examples/advanced/Cargo.toml
- examples/providers/examples/dyn_provider.rs
- scripts/run.sh
Demonstrate the `DynProvider`
Required in https://github.com/alloy-rs/book/pull/71
> feat: DynProvider

- README.md
- examples/providers/examples/mocking.rs
Closes #185 
Supersedes #202 
- Demonstrate how to mock a provider
> feat: mocking a provider

- README.md
- examples/sol-macro/Cargo.toml
- examples/sol-macro/examples/abi/Colors.json
- examples/sol-macro/examples/all_derives.rs
- examples/sol-macro/examples/extra_derives.rs
Closes #192 
- Demonstrate `all_derives` attribute
- Demonstrate `extra_derives` attribute (applied globally)
> feat: sol marco derive attributes

- examples/contracts/examples/interact_with_abi.rs
- examples/layers/examples/fallback_layer.rs
- examples/node-bindings/examples/anvil_fork_instance.rs
- examples/node-bindings/examples/anvil_fork_provider.rs
- examples/node-bindings/examples/anvil_set_storage_at.rs
- examples/providers/examples/batch_rpc.rs
- examples/providers/examples/http.rs
- examples/providers/examples/http_with_auth.rs
- examples/providers/examples/multicall.rs
- examples/providers/examples/multicall_batching.rs
- examples/queries/examples/query_contract_storage.rs
- examples/queries/examples/query_deployed_bytecode.rs
- examples/queries/examples/query_logs.rs
- examples/transactions/examples/gas_price_usd.rs
- examples/transactions/examples/permit2_signature_transfer.rs
- examples/transactions/examples/trace_call.rs
- examples/transactions/examples/trace_transaction.rs
- examples/transactions/examples/transfer_erc20.rs
- examples/wallets/examples/ledger_signer.rs
- examples/wallets/examples/trezor_signer.rs
- examples/wallets/examples/yubi_signer.rs
Replace merkle with ithaca public RPC
> chore: use ithaca rpc

- Cargo.toml
- benches/BENCHMARKS.md
- benches/Cargo.toml
- benches/benches/dyn_encoding.rs
- benches/benches/static_encoding.rs
- benches/benches/u256.rs
- benches/src/alloy_helpers.rs
- benches/src/ethers_helpers.rs
- benches/src/lib.rs
Moving benches from the internal private repository.
Benchmark alloy core primitives against ethers-rs.
Benches: 
- Dynamic ABI Encoding
- Static ABI Encoding
- U256 Operations bench using Uniswap v2 swap calculations
> feat: benches

- README.md
- examples/fillers/Cargo.toml
- examples/fillers/examples/urgent_filler.rs
- examples/layers/examples/delay_layer.rs
- examples/providers/examples/basic_provider.rs
Aggregating all code examples from the internal writeups here, so that these can be used in the book as snippets as well.
> feat: migrate examples from writeups

- Cargo.toml
- examples/wallets/Cargo.toml
- examples/wallets/examples/gcp_signer.rs
> use chain id in example
