README.md, examples/big-numbers/Cargo.toml, examples/big-numbers/examples/comparison_equivalence.rs, examples/big-numbers/examples/conversion.rs, examples/big-numbers/examples/create_instances.rs, examples/big-numbers/examples/math_operations.rs, examples/big-numbers/examples/math_utilities.rs
To add examples from `ethers-rs`: `big-numbers`
Implements the examples from `ethers-rs`.
Largely implements the same features except for Serde's `Numeric` value as that does not seem to be compatible.
=> feat(big-numbers): Port `big-numbers` from `ethers-rs`

Cargo.toml, examples/big-numbers/Cargo.toml, examples/big-numbers/examples/comparison_equivalence.rs, examples/big-numbers/examples/conversion.rs, examples/big-numbers/examples/create_instances.rs, examples/big-numbers/examples/math_operations.rs, examples/big-numbers/examples/math_utilities.rs, examples/wallets/Cargo.toml, examples/wallets/examples/ledger_signer.rs, examples/wallets/examples/mnemonic_signer.rs, examples/wallets/examples/private_key_signer.rs, examples/wallets/examples/sign_message.rs, examples/wallets/examples/sign_permit_hash.rs, examples/wallets/examples/trezor_signer.rs, examples/wallets/examples/yubi_signer.rs
Supersedes #10 by not including the flattened directory structure as there is alignment on using the `alloy` namespace but not the earlier proposed directory structure.
Once merged will backport the change to the individual pending PRs.
=> fix(general): use alloy namespace

README.md, examples/contracts/Cargo.toml, examples/contracts/examples/abi/Counter.json, examples/contracts/examples/abi/IERC20.json, examples/contracts/examples/artifacts/Counter.json, examples/contracts/examples/deploy_from_artifact.rs, examples/contracts/examples/deploy_from_contract.rs, examples/contracts/examples/generate.rs
To add examples from `ethers-rs`: `contracts`
Implements a subset of the examples in `ethers-rs` as they are largely already covered by other examples or the implementation was missing. I've made some modifications to make it better fit for Alloy.
I have not included the contract compilation flow as Alloy does not re-export `solc`.
Marked as blocked until https://github.com/alloy-rs/alloy/pull/326 is merged
=> feat(contracts): Port `contracts` from `ethers-rs`

README.md, examples/layers/Cargo.toml, examples/layers/examples/nonce_layer.rs, examples/layers/examples/signer_layer.rs
To add examples from `ethers-rs`: `middleware` (layers)
Implements a subset of the examples from `ethers-rs`, specifically the `NonceManagerMiddleware` and the `SignerMiddleware`.
Currently not implemented as an example, due to the implementation missing in Alloy:
- `GasEscalatorMiddleware`
- `GasOracleMiddleware`
- `PolicyMiddleware`
Some examples are not implemented due to the builder pattern being used throughout all examples in Alloy.
`CustomMiddleware` has not been implemented yet as I think it likely will require some implementation work to be able to define a robust way of handling this. Users can refer to the existing implementations as a starting point.
I've decided to refer to these as `layers` rather than `ether-rs`'s `middleware`.
=> feat(layers): Port `middleware` (layers) from `ethers-rs`

Cargo.toml, examples/wallets/Cargo.toml, examples/wallets/examples/sign_permit_hash.rs
`alloy::sol` overrides the `alloy_sol_types` import with `alloy::sol_types`, and should be used instead of the inner `alloy::sol_types::sol`.
=> fix: use `alloy::sol` instead of `alloy::sol_types::sol`

.github/workflows/ci.yml, .github/workflows/dependencies.yml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/test.yml, examples/anvil/examples/fork_anvil.rs, examples/contracts/examples/generate.rs, examples/providers/examples/builder.rs, examples/subscriptions/examples/event_multiplexer.rs, examples/subscriptions/examples/subscribe_blocks.rs, examples/subscriptions/examples/watch_contract_event.rs, examples/transactions/examples/gas_price_usd.rs, examples/transactions/examples/trace_call.rs, examples/transactions/examples/trace_transaction.rs, examples/transactions/examples/transfer_erc20.rs, examples/transactions/examples/transfer_eth.rs
Closes #19
Adds multiple Github workflows:
- `lint` (clippy and fmt)
- `test` (runs a build check and the examples)
- `integration` (runs daily against current pinned version of `alloy` and latest commit on main of `alloy`)
- `dependencies` (runs weekly, opens a ticket with outdated dependencies and proposed new ones)
Does not yet have integration set up with Discord webhooks
=> Add Github CI workflow

.github/workflows/lint.yml, Cargo.toml, examples/layers/examples/nonce_layer.rs, examples/layers/examples/recommended_layers.rs, examples/layers/examples/signer_layer.rs, examples/providers/Cargo.toml, examples/subscriptions/Cargo.toml
Closes #35 
Updates to latest Alloy / Alloy Core commit, renames `ManagedNonceLayer` to `NonceManagerLayer`.
Adds small comment fix and enhance Clippy linting rules.
=> [Fix] Rename `ManagedNonceLayer` to `NonceManagerLayer`

.github/workflows/integration.yml, Cargo.toml, examples/providers/Cargo.toml, examples/providers/examples/connect_builtin.rs, examples/providers/examples/http.rs, examples/providers/examples/ipc.rs, examples/providers/examples/ws.rs, examples/providers/examples/ws_with_auth.rs, examples/queries/examples/query_contract_storage.rs, examples/queries/examples/query_deployed_bytecode.rs, examples/queries/examples/query_logs.rs, examples/subscriptions/Cargo.toml, examples/subscriptions/examples/event_multiplexer.rs, examples/subscriptions/examples/subscribe_blocks.rs, examples/subscriptions/examples/watch_contract_event.rs, examples/transactions/examples/gas_price_usd.rs, examples/transactions/examples/trace_call.rs, examples/transactions/examples/trace_transaction.rs, examples/transactions/examples/transfer_erc20.rs, examples/transactions/examples/transfer_eth.rs
Closes #25 
Pulls in latest changes, fixes breaking ones. In some instances I've preferred to use the `ProviderBuilder` rather than the `RootProvider`, except in cases where we want to showcase the `RootProvider`.
0.7.0 of `alloy-core` does not require us to use ` [patch.crates-io] ` anymore.
Also fixes the broken intergration CI runs: https://github.com/alloy-rs/examples/actions/workflows/integration.yml / https://github.com/alloy-rs/examples/actions/runs/8510143328/job/23307105840
=> [Debt] Update to latest Alloy and remove patches from Cargo.toml + CI

.github/workflows/integration.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md, examples/subscriptions/examples/poll_logs.rs, examples/subscriptions/examples/subscribe_logs.rs
Follow up for #59 
Tags example as non-runnable, clarify difference between polling and subscribing
=> Tag `subscribe_logs` as non-runnable, follow up for #59

examples/wallets/examples/private_key_signer.rs
As the name of the example file, some people may need this operation to implement some quick testing or automated procedures. But security is really important, so I put risk warnings in prominent places to increase people's security awareness.
=> add comment: risk warning and how to set up signer from private key

examples/transactions/examples/send_raw_transaction.rs
Addresses: https://github.com/alloy-rs/alloy/issues/283#issuecomment-2161061664
Added explanatory snippet explaining convenience method
=> chore(transactions) use `send_tx_envelope` rather than manually encoding and calling `send_raw_transaction`

examples/fillers/examples/gas_filler.rs, examples/fillers/examples/nonce_filler.rs, examples/fillers/examples/recommended_fillers.rs, examples/fillers/examples/signer_filler.rs, examples/providers/examples/builder.rs, examples/transactions/examples/send_eip1559_transaction.rs, examples/transactions/examples/send_eip4844_transaction.rs, examples/transactions/examples/send_legacy_transaction.rs, examples/transactions/examples/send_private_transaction.rs, examples/transactions/examples/send_raw_transaction.rs, examples/transactions/examples/trace_call.rs, examples/transactions/examples/transfer_eth.rs, examples/transactions/examples/with_access_list.rs, examples/wallets/examples/keystore_signer.rs, examples/wallets/examples/ledger_signer.rs, examples/wallets/examples/mnemonic_signer.rs, examples/wallets/examples/private_key_signer.rs, examples/wallets/examples/trezor_signer.rs, examples/wallets/examples/yubi_signer.rs
- Only set `from` field if required (i.e. signer not set in provider or not the first signer)
- Cleans up some documentation as well
=> fix(general): only set `.with_from field` if required

Cargo.toml, README.md, examples/contracts/Cargo.toml, examples/contracts/examples/abi/Colors.json, examples/contracts/examples/contract_instance.rs, examples/contracts/examples/dyn_sol_struct_tuples.rs
Show how to interact with an already deployed contract. 
Use the `ContractInstance` interface.
=> feat(contract): interact using `ContractInstance`

.github/workflows/integration.yml, .github/workflows/test.yml, README.md, examples/advanced/Cargo.toml, examples/advanced/examples/any_network.rs
Resolves #85 
Adds an example that uses `AnyNetwork` to extract the extra fields of an Arbitrum transaction receipt: `gasUsedForL1` and `l1BlockNumber`.
Did not use `anvil` since we want to get the receipts from an Arbitrum network. As such, added this example to the list of ignored ones in CI. Lmk if there's a way this could be improved.
=> feat(advanced): use AnyNetwork to get Arbitrum receipts' extra fields

CONTRIBUTING.md, Cargo.toml, examples/transactions/examples/send_eip7702_transaction.rs, scripts/run.sh
- Bumps dependencies
- Fixes broken example due to API change
- Adds script to easily run all examples
=> chore: bump alloy to 0.3.5 and add script to run all examples

Cargo.toml, clippy.toml, examples/advanced/Cargo.toml, examples/advanced/examples/foundry_fork_db.rs
The fork-db functionality was extracted from foundry as `foundry-fork-db`. This is a generic tool to create and manage forks. 
foundry's current forking mechanism and management of multiple forks is based on this. 
Demonstrate a minimal example of how this works using `SharedBackend` and `BlockchainDb`.
=> feat(`advanced`): foundry-fork-db

.github/workflows/test.yml, Cargo.toml, README.md, examples/advanced/Cargo.toml, examples/advanced/examples/reth_db_layer.rs, examples/advanced/examples/reth_db_provider.rs
In the latest release of alloy-0.3.6, `ProviderCall` was introduced as a return type in the `Provider` trait.
`ProviderCall` enables to fetch the result of an RPC call from any data source such as the node's db, cache etc. 
More on this can be found here https://github.com/alloy-rs/alloy/pull/788
Example showing how to wrap the `Provider` trait over reth-db and use `ProviderCall` to fetch responses from the db directly.
=> feat(advanced): `Provider` trait over reth-db

Cargo.toml, examples/advanced/Cargo.toml, examples/layers/Cargo.toml, examples/providers/examples/ws_with_auth.rs, examples/transactions/examples/send_eip7702_transaction.rs, examples/wallets/Cargo.toml
Bumps Alloy to `0.5.2`
Updates Alloy to `0.5.2` as well as all other dependencies (incl. `revm` to fix a perceived breaking in `foundry-fork-db`).
=> chore: bump to 0.5.2

README.md, examples/providers/examples/http_with_auth.rs
Closes #153 
Instantiate a `reqwest::Client` with the `AUTHORIZATION` header.
=> feat: HTTP with auth header

README.md, examples/providers/examples/batch_rpc.rs
Demonstrate how to make a batch request.
Batch and send request using `RpcClient`
=> feat: JSON-RPC batch request

README.md, examples/transactions/examples/debug_trace_call_many.rs, examples/transactions/examples/trace_call_many.rs, scripts/run.sh
Closes: https://github.com/alloy-rs/examples/issues/121
- Add example implementation for `trace_call_many`
- Add example implementation for `debug_trace_call_many`
=> feat: add example for trace_call_many and debug_trace_call_many

Cargo.toml, README.md, examples/wallets/Cargo.toml, examples/wallets/examples/aws_signer.rs, examples/wallets/examples/gcp_signer.rs, scripts/run.sh
Closes: https://github.com/alloy-rs/examples/issues/14
=> feat: add gcp-signer

Cargo.toml, examples/wallets/Cargo.toml
Bumps to Alloy `0.8`, Foundry's fork DB to `0.9`
Note: `gcloud-sdk` has a new `0.26` version available but this is not yet updated in Alloy
=> chore: bump deps, foundry-fork-db to `0.9`, alloy to `0.8`

examples/providers/examples/multicall.rs
Remove unnecessary comments from multicall
=> chore: rm comments

README.md, examples/advanced/examples/any_network.rs, examples/fillers/examples/wallet_filler.rs, examples/providers/examples/builder.rs, examples/subscriptions/examples/event_multiplexer.rs, examples/subscriptions/examples/poll_logs.rs, examples/transactions/examples/send_eip7702_transaction.rs, examples/wallets/examples/ethereum_wallet.rs, examples/wallets/examples/keystore_signer.rs, examples/wallets/examples/ledger_signer.rs, examples/wallets/examples/private_key_signer.rs, examples/wallets/examples/trezor_signer.rs, examples/wallets/examples/yubi_signer.rs, scripts/run.sh
Closes #197 
Closes #56 
- Replace all instances of `EthereumWallet` being passed to `.wallet(..)` with directly passing the signer.
- Demonstrate `EthereumWallet` in a separate example.
=> feat: use signers in provider and demonstrate EthereumWallet

README.md, examples/providers/examples/multicall_batching.rs
Closes #196 
Supersedes #203 
- Demonstrate `CallBatchLayer` 
@DaniPopes ptal
=> feat: CallBatchLayer

.github/workflows/integration.yml, .github/workflows/test.yml, CONTRIBUTING.md, scripts/test.sh
Speed up CI by building the examples once and then running them in parallel, now possible as we are using our own RPCs
Cuts down to < 3 mins without a build cache, down from 10 mins+ with
=> chore(`ci`): speed up CI

examples/transactions/examples/permit2_signature_transfer.rs
Closes #218 
People are 7702 authorizing default anvil accounts, which leads to permit2 failure.
> But for 7702 accounts, it would make sense if permit2 starts failing.
Because if the EOA is authorized, instead of using ECDSA.recover, the permit2 SignatureChecker lib would use 1271 signature verification first. 
Temp fix by using last two accounts which haven't been authorized
=> fix(`txs`): permit2_sig by using last two anvil accounts

examples/providers/examples/multicall_batching.rs
Saw a mismatch in comments and code for an multicall example
Chose the lower duration value. Feel free to close this PR since it's a typo, just wanted to highlight
=> fix: use correct duration for mulitcall batching

Cargo.toml, examples/transactions/Cargo.toml, examples/transactions/examples/permit2_signature_transfer.rs, examples/wallets/Cargo.toml
This PR is to fix this [concern](https://github.com/alloy-rs/examples/pull/229#issuecomment-3053173254).
It's an extension of #229.
- Introduced a new helper function `generate_mnemonic()` to generate a random 12-word English mnemonic.
- This generated mnemonic is then passed to the `.mnemonic(...)` method when initializing the Anvil instance, replacing the previously hardcoded static phrase.
=> Replace hardcoded mnemonic with a randomly generated one
